# Pull the Node image from Docker Hub
FROM node:17

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

EXPOSE 5000

# Run the server
CMD ["npm", "start"]